services:
    postgresql:
        container_name: GroceryStorePostgresql
        image: library/postgres:16.3-alpine3.20
        ports:
            - 5432:5432
        volumes:
            - $PWD/.local/data/pg16:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=grocery
            - POSTGRES_PASSWORD=grocery
            - POSTGRES_DB=grocery
        networks:
            - custom


networks:
    custom:
        driver: bridge
